name: wafer_database
channels:
  - conda-forge
  - apple
dependencies:
  - atk-1.0=2.38.0
  - atpublic=5.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bidict=0.23.1
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - contourpy=1.3.1
  - cycler=0.12.1
  - dash=2.18.2
  - dash-ag-grid=31.2.0
  - dash-bootstrap-components=1.6.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - et_xmlfile=2.0.0
  - filelock=3.16.1
  - flask=3.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - graphviz=12.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h2=4.1.0
  - harfbuzz=10.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - ibis-framework-core=9.5.0
  - ibis-sqlite=9.5.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libparquet=18.1.0
  - libpng=1.6.45
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mdurl=0.1.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.2.1
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.4.0
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.0
  - parsy=2.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - plotly=5.24.1
  - pthread-stubs=0.4
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.13.1
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.20.3
  - python-tzdata=2024.2
  - python_abi=3.13
  - pytz=2024.1
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - retrying=1.3.3
  - rich=13.9.4
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlglot=25.20.1
  - tenacity=9.0.0
  - tk=8.6.13
  - toolz=0.12.1
  - tornado=6.4.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
